"""ADCOS connectivity-contract core (M002 — Connectivity Contract Core).

Public surface:

- the canonical durable object ``ConnectivityContract`` (LOCK-101) and its
  frozen 1.1 §3 field set;
- the contract-level lifecycle state machine and command vocabulary;
- the contract lease model (LOCK-117: contract-scoped right-to-use);
- ``ContractStore``: the deterministic journal fold (construction-is-
  recovery) and the sole writer of contract state.
"""

from .model import (
    ASSURANCE_STATES,
    COMMAND_KINDS,
    CONSTRAINT_KINDS,
    CONTRACT_STATES,
    CONTRACT_TRANSITIONS,
    LEASE_STATES,
    PRINCIPAL_KINDS,
    REFERENCE_KINDS,
    TERMINAL_STATES,
    TERMINATION_CONDITION_KINDS,
    ActivateContract,
    BeneficiaryScope,
    BindExecutionArtifact,
    ConnectivityContract,
    ConnectivityPrincipal,
    ContractError,
    ContractLease,
    ContractReason,
    CreateContract,
    ExpireContract,
    ExpireLease,
    FailContract,
    GrantLease,
    HardConstraint,
    OpaqueReference,
    Provenance,
    RecordAssurance,
    RecordDelivery,
    RecordExecutionActivation,
    RecordSettled,
    RecordSettlementPending,
    RecordUsageFinal,
    RenewLease,
    RevokeLease,
    SelectOffers,
    TerminateContract,
    TerminationRules,
    ValidityInterval,
    apply_command,
    build_contract,
    build_lease,
    check_transition,
    derive_contract_id,
)
from .store import CommandRecord, ContractStore, MergeResult

__all__ = [
    "ASSURANCE_STATES",
    "COMMAND_KINDS",
    "CONSTRAINT_KINDS",
    "CONTRACT_STATES",
    "CONTRACT_TRANSITIONS",
    "LEASE_STATES",
    "PRINCIPAL_KINDS",
    "REFERENCE_KINDS",
    "TERMINAL_STATES",
    "TERMINATION_CONDITION_KINDS",
    "ActivateContract",
    "BeneficiaryScope",
    "BindExecutionArtifact",
    "CommandRecord",
    "ConnectivityContract",
    "ConnectivityPrincipal",
    "ContractError",
    "ContractLease",
    "ContractReason",
    "ContractStore",
    "CreateContract",
    "ExpireContract",
    "ExpireLease",
    "FailContract",
    "GrantLease",
    "HardConstraint",
    "MergeResult",
    "OpaqueReference",
    "Provenance",
    "RecordAssurance",
    "RecordDelivery",
    "RecordExecutionActivation",
    "RecordSettled",
    "RecordSettlementPending",
    "RecordUsageFinal",
    "RenewLease",
    "RevokeLease",
    "SelectOffers",
    "TerminateContract",
    "TerminationRules",
    "ValidityInterval",
    "apply_command",
    "build_contract",
    "build_lease",
    "check_transition",
    "derive_contract_id",
]
