/**
 * The operation EXECUTOR — runs a coverage-registry operation through
 * Worker 1's typed client. The API Explorer executes every operation
 * here; the error workbench's retry resolves a captured request back to
 * its operation and re-executes it the same way.
 *
 * Honesty rules:
 * - ONLY registry operations are executable (`coverageByOperation` is
 *   the gate — an unsupported operation never reaches this module).
 * - Every execution is a REAL request through the typed client (no
 *   mocked responses presented as backend truth, ever).
 * - Local validation problems (missing path parameters, malformed JSON)
 *   are reported as `kind: "invalid"` with a plain message — NEVER
 *   fabricated as backend reason codes.
 */

import type { AdcosClient } from "@/lib/api/client";
import { AdcosApiError, isAdcosApiError } from "@/lib/api/errors";
import { COVERAGE, coverageByOperation, type CoverageRecord } from "@/lib/api/coverage";
import type {
  AcceptOffersInput,
  ActivateContractInput,
  CreateIntentInput,
  LeaseWindowInput,
  ListParams,
  RegisterWebhookEndpointInput,
  RevokeLeaseInput,
  TerminateContractInput,
} from "@/lib/api/types";

/** The descriptor of the request an execution actually made. */
export interface RequestDescriptor {
  method: string;
  path: string;
  body?: unknown;
  /** The idempotency key sent (mutations only). */
  idempotencyKey?: string;
}

export type ExecuteOutcome =
  | {
      kind: "success";
      /** The HTTP status (the boundary's success discipline is 200). */
      status: number;
      /** The parsed response payload (envelope or platform body). */
      payload: unknown;
      request: RequestDescriptor;
      coverage: CoverageRecord;
    }
  | {
      kind: "error";
      /** The typed error — reason VERBATIM for rendering. */
      error: AdcosApiError;
      request: RequestDescriptor;
      coverage: CoverageRecord;
    }
  | {
      /** Local validation failure (never a fabricated backend reason). */
      kind: "invalid";
      message: string;
      coverage: CoverageRecord;
    };

export interface ExecuteInput {
  /** The coverage-registry operation id. */
  operation: string;
  /** Path parameter values keyed by template name ({intent_id} → …). */
  pathParams?: Record<string, string>;
  /**
   * The request body (mutations and the GET-body list discipline).
   * A string is parsed as JSON first (the explorer's editor output).
   */
  body?: unknown;
  /**
   * Caller-supplied idempotency key for mutations (a fresh one is
   * generated by the client when omitted — the boundary owns the
   * discipline; supplying one makes the curl reproduction exact).
   */
  idempotencyKey?: string;
}

/** The operations whose effect is destructive — UIs must confirm first. */
export const DESTRUCTIVE_OPERATIONS: ReadonlySet<string> = new Set([
  "contract_terminate",
  "lease_revoke",
]);

/** Parse a template path's parameter names ("/api/2.0/intents/{intent_id}" → ["intent_id"]). */
export function pathParameterNames(template: string): string[] {
  return [...template.matchAll(/\{([a-z_]+)\}/g)].map((match) => match[1]);
}

/** Render a coverage path template with concrete parameter values. */
export function renderPath(
  template: string,
  params: Record<string, string>,
): string {
  return template.replace(
    /\{([a-z_]+)\}/g,
    (_, name: string) => params[name] ?? `{${name}}`,
  );
}

/**
 * Resolve a concrete (method, path) back to its coverage record and the
 * path parameters it carried — the inspector's "which API operation
 * produced/changed this object" and the workbench's retry both use it.
 * Returns null for any path outside the registry (honest: never a guess).
 */
export function matchOperationForPath(
  method: string,
  path: string,
): { record: CoverageRecord; params: Record<string, string> } | null {
  const upper = method.toUpperCase();
  const segments = path.split("/").filter((segment) => segment.length > 0);
  let best: {
    record: CoverageRecord;
    params: Record<string, string>;
    literals: number;
  } | null = null;

  for (const record of COVERAGE) {
    const methodsMatch =
      record.method === upper ||
      // the demo operation is GET|POST on one route (POST carries the instant)
      (record.operation === "demo_contract_fulfillment" && upper === "POST");
    if (!methodsMatch) continue;
    const templateSegments = record.path
      .split("/")
      .filter((segment) => segment.length > 0);
    if (templateSegments.length !== segments.length) continue;

    const params: Record<string, string> = {};
    let literalMatches = 0;
    let ok = true;
    for (let index = 0; index < templateSegments.length; index += 1) {
      const templateSegment = templateSegments[index];
      const segment = segments[index];
      const paramMatch = /^\{([a-z_]+)\}$/.exec(templateSegment);
      if (paramMatch) {
        params[paramMatch[1]] = decodeURIComponent(segment);
      } else if (templateSegment === segment) {
        literalMatches += 1;
      } else {
        ok = false;
        break;
      }
    }
    if (!ok) continue;
    if (best === null || literalMatches > best.literals) {
      best = { record, params, literals: literalMatches };
    }
  }
  return best ? { record: best.record, params: best.params } : null;
}

/**
 * Execute one registry operation through the typed client. The dispatch
 * is exhaustive over the registry — an operation outside it returns
 * `kind: "invalid"` without ever touching the network (unsupported
 * operations are never callable).
 */
export async function executeOperation(
  client: AdcosClient,
  input: ExecuteInput,
): Promise<ExecuteOutcome> {
  const record = coverageByOperation(input.operation);
  if (record === undefined) {
    return {
      kind: "invalid",
      message: `"${input.operation}" is not a supported operation — the registry is the single source of truth.`,
      coverage: {
        operation: input.operation,
        method: "GET",
        path: "",
        mutation: false,
        requiredCapability: "",
        platform: false,
        uiLocation: "",
        description: "",
      },
    };
  }

  // path parameters: every template param must be provided, no extras
  const names = pathParameterNames(record.path);
  const params: Record<string, string> = {};
  for (const name of names) {
    const value = input.pathParams?.[name]?.trim();
    if (!value) {
      return {
        kind: "invalid",
        message: `Path parameter ${name} is required for ${record.method} ${record.path}.`,
        coverage: record,
      };
    }
    params[name] = value;
  }
  const extras = Object.keys(input.pathParams ?? {}).filter(
    (name) => !names.includes(name),
  );
  if (extras.length > 0) {
    return {
      kind: "invalid",
      message: `Unknown path parameter(s) for this operation: ${extras.join(", ")}.`,
      coverage: record,
    };
  }

  // body: a string is the editor's raw JSON — parse it locally first
  let body: unknown = input.body;
  if (typeof body === "string") {
    if (body.trim().length === 0) {
      body = undefined;
    } else {
      try {
        body = JSON.parse(body);
      } catch (error) {
        return {
          kind: "invalid",
          message: `The request body is not valid JSON: ${
            error instanceof Error ? error.message : String(error)
          }`,
          coverage: record,
        };
      }
    }
  }

  const renderedPath = renderPath(record.path, params);
  const idempotencyKey = record.mutation
    ? input.idempotencyKey?.trim() || undefined
    : undefined;

  // the demo operation's effective shape: GET (default instant) unless
  // the body carries {"instant"} — then POST (the client does exactly this)
  const demoInstant =
    record.operation === "demo_contract_fulfillment" &&
    typeof body === "object" &&
    body !== null &&
    "instant" in body
      ? String((body as { instant?: unknown }).instant ?? "")
      : "";
  const effective =
    record.operation === "demo_contract_fulfillment"
      ? demoInstant
        ? { method: "POST" as const, body: { instant: demoInstant } as unknown }
        : { method: "GET" as const, body: undefined as unknown }
      : { method: record.method, body };
  const descriptor: RequestDescriptor = {
    method: effective.method,
    path: renderedPath,
    body: effective.body,
    idempotencyKey: usedKey(idempotencyKey),
  };

  try {
    // the exhaustive dispatch — every branch is a REAL typed call.
    // (COVERAGE is typed `CoverageRecord[]`, so exhaustiveness is
    // pinned by the explorer test suite — every registry operation
    // must have a dispatch branch here.)
    switch (record.operation) {
      case "healthz":
        return success(record, 200, await client.healthz(), descriptor);
      case "readyz":
        return success(record, 200, await client.readyz(), descriptor);
      case "demo_contract_fulfillment":
        return success(
          record,
          200,
          await client.demoContractFulfillment(demoInstant || undefined),
          descriptor,
        );
      case "platform_contract_read":
        return success(
          record,
          200,
          await client.platformContractRead(params.contract_id),
          descriptor,
        );
      case "application_self":
        return success(record, 200, await client.applicationSelf(), descriptor);
      case "intent_create":
        return success(
          record,
          200,
          await client.createIntent(body as CreateIntentInput, { idempotencyKey }),
          descriptor,
        );
      case "intents_list":
        return success(
          record,
          200,
          await client.listIntents(body as ListParams),
          descriptor,
        );
      case "intent_get":
        return success(record, 200, await client.getIntent(params.intent_id), descriptor);
      case "intent_lifecycle":
        return success(
          record,
          200,
          await client.getIntentLifecycle(params.intent_id),
          descriptor,
        );
      case "offers_accept":
        return success(
          record,
          200,
          await client.acceptOffers(params.intent_id, body as AcceptOffersInput, {
            idempotencyKey,
          }),
          descriptor,
        );
      case "contract_activate":
        return success(
          record,
          200,
          await client.activateContract(params.intent_id, body as ActivateContractInput, {
            idempotencyKey,
          }),
          descriptor,
        );
      case "contracts_list":
        return success(
          record,
          200,
          await client.listContracts(body as ListParams),
          descriptor,
        );
      case "contract_get":
        return success(
          record,
          200,
          await client.getContract(params.contract_id),
          descriptor,
        );
      case "contract_usage":
        return success(
          record,
          200,
          await client.getContractUsage(params.contract_id),
          descriptor,
        );
      case "contract_assurance":
        return success(
          record,
          200,
          await client.getContractAssurance(params.contract_id),
          descriptor,
        );
      case "contract_terminate":
        return success(
          record,
          200,
          await client.terminateContract(
            params.contract_id,
            body as TerminateContractInput,
            { idempotencyKey },
          ),
          descriptor,
        );
      case "lease_grant":
        return success(
          record,
          200,
          await client.grantLease(params.contract_id, body as LeaseWindowInput, {
            idempotencyKey,
          }),
          descriptor,
        );
      case "leases_list":
        return success(record, 200, await client.listLeases(body as ListParams), descriptor);
      case "lease_get":
        return success(record, 200, await client.getLease(params.lease_id), descriptor);
      case "lease_renew":
        return success(
          record,
          200,
          await client.renewLease(params.lease_id, body as LeaseWindowInput, {
            idempotencyKey,
          }),
          descriptor,
        );
      case "lease_revoke":
        return success(
          record,
          200,
          await client.revokeLease(params.lease_id, body as RevokeLeaseInput, {
            idempotencyKey,
          }),
          descriptor,
        );
      case "endpoints_list":
        return success(
          record,
          200,
          await client.listWebhookEndpoints(body as ListParams),
          descriptor,
        );
      case "endpoint_register":
        return success(
          record,
          200,
          await client.registerWebhookEndpoint(body as RegisterWebhookEndpointInput, {
            idempotencyKey,
          }),
          descriptor,
        );
      case "endpoint_get":
        return success(
          record,
          200,
          await client.getWebhookEndpoint(params.endpoint_id),
          descriptor,
        );
      case "deliveries_list":
        return success(
          record,
          200,
          await client.listDeliveries(params.endpoint_id, body as ListParams),
          descriptor,
        );
      default:
        // unreachable while the dispatch covers the registry — the
        // explorer tests pin this (every registry operation dispatches)
        return {
          kind: "invalid",
          message: `Operation ${record.operation} is registered but not wired in this console build.`,
          coverage: record,
        };
    }
  } catch (error) {
    if (isAdcosApiError(error)) {
      return { kind: "error", error, request: descriptor, coverage: record };
    }
    return {
      kind: "invalid",
      message: error instanceof Error ? error.message : String(error),
      coverage: record,
    };
  }
}

function success(
  coverage: CoverageRecord,
  status: number,
  payload: unknown,
  request: RequestDescriptor,
): ExecuteOutcome {
  return { kind: "success", status, payload, request, coverage };
}

function usedKey(key: string | undefined): string | undefined {
  return key && key.length > 0 ? key : undefined;
}

/**
 * The curl headers an operation's request carries — with the credential
 * ALWAYS masked (the real value never leaves the session store; the
 * reproduction is copyable without leaking it). The application id is
 * filled with the session's ACTUAL value when known.
 */
export function maskedRequestHeaders(options: {
  platform: boolean;
  mutation: boolean;
  applicationId?: string | null;
  idempotencyKey?: string | null;
}): { name: string; value: string }[] {
  const headers: { name: string; value: string }[] = [];
  if (!options.platform) {
    headers.push({
      name: "X-ADCOS-Application",
      value: options.applicationId ?? "<your-application-id>",
    });
    headers.push({ name: "X-ADCOS-Credential", value: "<your-credential>" });
    headers.push({ name: "X-ADCOS-API-Version", value: "2.0" });
  }
  if (options.mutation && options.idempotencyKey) {
    headers.push({ name: "X-ADCOS-Idempotency-Key", value: options.idempotencyKey });
  }
  return headers;
}
